[package]
name = "moonshine-runner"
version = "0.2.0"
authors = ["Maxwell Freudenburg"]
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
crossterm = "0.26.1"
